[project]
name = "apl_aws"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Michael Kingston", email = "71872141+mkingopng@users.noreply.github.com"},
]
dependencies = [
    "jupyter>=1.0.0",
    "boto3>=1.34.9",
    "pandas>=2.1.4",
    "flask>=3.0.0",
    "streamlit>=1.29.0",
    "pytest>=7.4.4",
    "werkzeug>=3.0.1",
    "python-dotenv>=1.0.0",
    "file-tree>=1.3.0",
    "flask-testing>=0.8.1",
    "pytest-mock>=3.12.0",
    "moto>=4.2.12",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
package-type = "application"
